// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package lesson_service

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeAPIGatewayInternalClientsLessonService(in *jlexer.Lexer, out *SetLessonReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "teacher_id":
			out.TeacherID = int64(in.Int64())
		case "lesson_name":
			out.LessonName = string(in.String())
		case "class_name":
			out.ClassName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeAPIGatewayInternalClientsLessonService(out *jwriter.Writer, in SetLessonReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"teacher_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TeacherID))
	}
	{
		const prefix string = ",\"lesson_name\":"
		out.RawString(prefix)
		out.String(string(in.LessonName))
	}
	{
		const prefix string = ",\"class_name\":"
		out.RawString(prefix)
		out.String(string(in.ClassName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SetLessonReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeAPIGatewayInternalClientsLessonService(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SetLessonReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeAPIGatewayInternalClientsLessonService(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SetLessonReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeAPIGatewayInternalClientsLessonService(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SetLessonReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeAPIGatewayInternalClientsLessonService(l, v)
}
